name: MoveLights
main: top.nkbe.MoveLights
version: 1.2.6
author: NkBe, _TwT
api-version: 1.17
commands:
  movel:
    description: 完整命令
    usage: §a/<command> help 查看帮助
permissions:
  movelights.help:
    description: "查看帮助"
    default: true
  movelights.reload:
    description: "重载插件配置"
    default: op
  movelights.toggle:
    description: "总开关移动光源"
    default: op
  movelights.player.use:
    description: "玩家能使用移动光源"
    default: true
  movelights.player.onoff:
    description: "玩家对自己开关移动光源"
    default: true