name: NyaEaMc
main: top.nkbe.NyaEaMc
version: 1.4.1
author: NkBe, _TwT
api-version: 1.17
commands:
  nyaea:
    description: 主命令
    usage: §a/<command> help 查看帮助
    aliases: [movel]
  tpa:
    description: 請求傳送到指定玩家
    usage: §a/tpa <玩家>
  tpahere:
    description: 請求指定玩家傳送到你
    usage: §a/tpahere <玩家>
  tpaccept:
    description: 接受傳送請求
    usage: §a/tpaccept [玩家]
  tpdeny:
    description: 拒絕傳送請求
    usage: §a/tpdeny [玩家]
  tpcancel:
    description: 取消自己送出的傳送請求或傳送讀秒
    usage: §a/tpcancel
permissions:
  nyaeamc.help:
    description: "查看帮助"
    default: true
  nyaeamc.reload:
    description: "重载插件配置"
    default: op
  nyaeamc.toggle:
    description: "总开关移动光源"
    default: op
  nyaeamc.player.use:
    description: "玩家能使用移动光源"
    default: true
  nyaeamc.player.onoff:
    description: "玩家对自己开关移动光源"
    default: true
  nyaeamc.note:
    description: "设定玩家备注"
    default: op
  nyaeamc.op:
    description: "可使用 /minecraft:op 授予其他玩家 op 权限"
    default: true
  nyaeamc.nick:
    description: "設定自己的暱稱"
    default: op
  nyaeamc.nick.others:
    description: "設定其他玩家的暱稱"
    default: op
  nyaeamc.nick.color:
    description: "在暱稱使用顏色代碼"
    default: op
  nyaeamc.chat.color:
    description: "在聊天使用顏色代碼"
    default: op
  nyaeamc.ping:
    description: "查看延遲"
    default: true
  nyaeamc.ping.others:
    description: "查看其他玩家的延遲"
    default: true
  nyaeamc.broadcast:
    description: "發送全服公告"
    default: op
  nyaeamc.heal:
    description: "治療玩家"
    default: op
  nyaeamc.feed:
    description: "補滿玩家飢餓值"
    default: op
  nyaeamc.fly:
    description: "切換飛行"
    default: op
  nyaeamc.speed:
    description: "設定移動速度"
    default: op
  nyaeamc.clearinventory:
    description: "清空背包"
    default: op
  nyaeamc.gamemode:
    description: "設定遊戲模式"
    default: op
  nyaeamc.weather:
    description: "設定天氣"
    default: op
  nyaeamc.time:
    description: "設定世界時間"
    default: op
  nyaeamc.invsee:
    description: "查看玩家背包"
    default: true
  nyaeamc.endersee:
    description: "查看玩家終界箱"
    default: op
  nyaeamc.tpa:
    description: "請求傳送到玩家"
    default: true
  nyaeamc.tpahere:
    description: "請求玩家傳送到自己"
    default: true
  nyaeamc.tpaccept:
    description: "接受傳送請求"
    default: true
  nyaeamc.tpdeny:
    description: "拒絕傳送請求"
    default: true
  nyaeamc.tpcancel:
    description: "取消傳送請求或讀秒"
    default: true
  nyaeamc.tpa.exempt.warmup:
    description: "跳過 TPA 傳送讀秒"
    default: op
  nyaeamc.tpa.exempt.cooldown:
    description: "跳過 TPA 請求冷卻"
    default: op
  nyaeamc.boatspeed:
    description: "強制設定 BoatFly 全局速度"
    default: op
