name: NyaEeMC
main: top.nkbe.NyaEeMC
version: 1.4.0
author: NkBe, _TwT
api-version: 1.17
commands:
  nyaee:
    description: 主命令
    usage: §a/<command> help 查看帮助
    aliases: [nyae, nyaemc, movel]
  nick:
    description: 設定暱稱
    usage: §a/nick <暱稱|off>
  realname:
    description: 由暱稱查詢真實玩家名
    usage: §a/realname <暱稱>
  ping:
    description: 查看延遲
    usage: §a/ping [玩家]
  broadcast:
    description: 發送全服公告
    usage: §a/broadcast <訊息>
    aliases: [bc]
  heal:
    description: 治療玩家
    usage: §a/heal [玩家]
  feed:
    description: 補滿玩家飢餓值
    usage: §a/feed [玩家]
  fly:
    description: 切換飛行
    usage: §a/fly [玩家]
  speed:
    description: 設定移動速度
    usage: §a/speed [walk|fly] <1-10>
  clearinventory:
    description: 清空背包
    usage: §a/clearinventory [玩家]
    aliases: [ci]
  boatspeed:
    description: 強制設定 BoatFly 全局速度
    usage: §a/boatspeed <0.1-50>
permissions:
  nyaemc.help:
    description: "查看帮助"
    default: true
  nyaemc.reload:
    description: "重载插件配置"
    default: op
  nyaemc.toggle:
    description: "总开关移动光源"
    default: op
  nyaemc.player.use:
    description: "玩家能使用移动光源"
    default: true
  nyaemc.player.onoff:
    description: "玩家对自己开关移动光源"
    default: true
  nyaemc.note:
    description: "设定玩家备注"
    default: op
  nyaemc.op:
    description: "可使用 /minecraft:op 授予其他玩家 op 权限"
    default: true
  nyaemc.nick:
    description: "設定自己的暱稱"
    default: true
  nyaemc.nick.others:
    description: "設定其他玩家的暱稱"
    default: op
  nyaemc.nick.color:
    description: "在暱稱使用顏色代碼"
    default: op
  nyaemc.chat.color:
    description: "在聊天使用顏色代碼"
    default: op
  nyaemc.ping:
    description: "查看延遲"
    default: true
  nyaemc.ping.others:
    description: "查看其他玩家的延遲"
    default: op
  nyaemc.broadcast:
    description: "發送全服公告"
    default: op
  nyaemc.heal:
    description: "治療玩家"
    default: op
  nyaemc.feed:
    description: "補滿玩家飢餓值"
    default: op
  nyaemc.fly:
    description: "切換飛行"
    default: op
  nyaemc.speed:
    description: "設定移動速度"
    default: op
  nyaemc.clearinventory:
    description: "清空背包"
    default: op
  nyaemc.boatspeed:
    description: "強制設定 BoatFly 全局速度"
    default: op
